Add currently processing status
helrond/fornax pull request #216
Opened 2021-12-09 19:58 UTC by bonniegee

Fixes #214

2021-12-09 20:04 UTC, helrond requested changes
One small tweak to more specifically target try/except. Also I think you need a migration?

2021-12-09 20:04 UTC, helrond commented on sip_assembly/routines.py
> +                    raise Exception(str(e), sip.bag_identifier)
I think how you did this in Pictor is better:

```suggestion
                try:
                    message = self.process_sip(sip)
                except Exception as e:
                    sip.process_status = self.start_status
                    sip.save()
                    raise Exception(str(e), sip.bag_identifier)
                 sip.process_status = self.end_status
                 sip.save()
```

2021-12-09 21:01 UTC, bonniegee commented
> One small tweak to more specifically target try/except. Also I think you need a migration?

Perhaps I am doing something wrong but literally nothing happens when I run `makemigrations` 🤔

2021-12-10 16:04 UTC, helrond commented
Hmm okay I would have thought that altering choices for a field would require a migration, but perhaps I am wrong!

2021-12-10 16:04 UTC, helrond approved these changes

2021-12-10 19:14 UTC, bonniegee commented
@helrond should I merge or wait for #215?

2021-12-10 22:11 UTC, helrond commented
I think you can merge - this is pretty low-risk.

2021-12-10 22:32 UTC, merged