Migrate from Travis CI to GitHub Actions
helrond/fornax pull request #338
Opened 2024-09-09 18:14 UTC by HaSistrunk

2024-09-09 23:31 UTC, helrond requested changes
Just need to move the branch enforcement rules, otherwise looks good!

2024-09-09 23:31 UTC, helrond commented on .github/enforcer.yml
> +name: 'Check Branch'
this file needs to be at `.github/workflows/enforcer.yml`

2024-09-10 13:23 UTC, helrond approved these changes

2024-09-11 17:09 UTC, p-galligan approved these changes

2024-09-11 17:43 UTC, merged